## Devbrat Anuragi
### 17078

# Linear Algebra

### Scalars (Rank 0 Tensors) in Base Python

In [1]:
x = 25
x

25

In [2]:
type(x) 

int

In [3]:
y = 3

In [4]:
py_sum = x + y
py_sum

28

In [5]:
type(py_sum)

int

In [6]:
x_float = 25.0
float_sum = x_float + y
float_sum

28.0

In [7]:
type(float_sum)

float

### Vectors (Rank 1 Tensors) in NumPy

In [8]:
import numpy as np 

In [9]:
x = np.array([25, 2, 5]) # type argument is optional, e.g.: dtype=torch.float16
x

array([25,  2,  5])

In [10]:
len(x)

3

In [11]:
x.shape

(3,)

In [12]:
type(x)

numpy.ndarray

In [13]:
x[0] # zero-indexed

25

In [14]:
type(x[0])

numpy.int32

### Vector Transposition

In [15]:
# Can't transpose a regular 1D array...
x_t = x.T
x_t

array([25,  2,  5])

In [16]:
x_t.shape

(3,)

In [17]:
# ...but can if we use nested "matrix-style" brackets: 
y = np.array([[25, 2, 5]])
y

array([[25,  2,  5]])

In [18]:
y.shape

(1, 3)

In [19]:
# ...but can transpose a matrix with a dimension of length 1, which is mathematically equivalent: 
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [20]:
y_t.shape # this is a column vector as it has 3 rows and 1 column

(3, 1)

In [21]:
# Column vector can be transposed back to original row vector: 
y_t.T 

array([[25,  2,  5]])

In [22]:
y_t.T.shape

(1, 3)

### Zero Vectors

Have no effect if added to another vector

In [23]:
z = np.zeros(3) 
z

array([0., 0., 0.])

### $L^2$ Norm

In [24]:
x

array([25,  2,  5])

In [25]:
(25**2 + 2**2 + 5**2)**(1/2)

25.573423705088842

In [26]:
np.linalg.norm(x)

25.573423705088842

So, if units in this 3-dimensional vector space are meters, then the vector $x$ has a length of 25.6m

**Return to slides here.**

### $L^1$ Norm

In [27]:
x

array([25,  2,  5])

In [28]:
np.abs(25) + np.abs(2) + np.abs(5)

32

### Squared $L^2$ Norm

In [29]:
x

array([25,  2,  5])

In [30]:
(25**2 + 2**2 + 5**2)

654

In [31]:
# we'll cover tensor multiplication more soon but to prove point quickly: 
np.dot(x, x)

654

**Return to slides here.**

### Max Norm

In [32]:
x

array([25,  2,  5])

In [33]:
np.max([np.abs(25), np.abs(2), np.abs(5)])

25

### Orthogonal Vectors

In [34]:
i = np.array([1, 0])
i

array([1, 0])

In [35]:
j = np.array([0, 1])
j

array([0, 1])

In [36]:
np.dot(i, j) # detail on the dot operation coming up...

0

### Matrices (Rank 2 Tensors) in NumPy

In [37]:
# Use array() with nested brackets: 
X = np.array([[25, 2], [5, 26], [3, 7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [38]:
X.shape

(3, 2)

In [39]:
X.size

6

In [40]:
# Select left column of matrix X (zero-indexed)
X[:,0]

array([25,  5,  3])

In [41]:
# Select middle row of matrix X: 
X[1,:]

array([ 5, 26])

In [42]:
# Another slicing-by-index example: 
X[0:2, 0:2]

array([[25,  2],
       [ 5, 26]])

### Tensor Transposition

In [43]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [44]:
X.T

array([[25,  5,  3],
       [ 2, 26,  7]])

### Basic Arithmetical Properties

Adding or multiplying with scalar applies operation to all elements and tensor shape is retained: 

In [45]:
X*2

array([[50,  4],
       [10, 52],
       [ 6, 14]])

In [46]:
X+2

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [47]:
X*2+2

array([[52,  6],
       [12, 54],
       [ 8, 16]])

If two tensors have the same size, operations are often by default applied element-wise. This is **not matrix multiplication**, which we'll cover later, but is rather called the **Hadamard product** or simply the **element-wise product**. 

The mathematical notation is $A \odot X$

In [48]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [49]:
A = X+2
A

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [50]:
A + X

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [51]:
A * X

array([[675,   8],
       [ 35, 728],
       [ 15,  63]])

### Reduction

Calculating the sum across all elements of a tensor is a common operation. For example: 

* For vector ***x*** of length *n*, we calculate $\sum_{i=1}^{n} x_i$
* For matrix ***X*** with *m* by *n* dimensions, we calculate $\sum_{i=1}^{m} \sum_{j=1}^{n} X_{i,j}$

In [52]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [53]:
X.sum()

68

### The Dot Product

In [54]:
x

array([25,  2,  5])

In [55]:
y = np.array([0, 1, 2])
y

array([0, 1, 2])

In [56]:
25*0 + 2*1 + 5*2

12

In [57]:
np.dot(x, y)

12

## Segment 3: Matrix Properties

### Frobenius Norm

In [58]:
X = np.array([[1, 2], [3, 4]])
X

array([[1, 2],
       [3, 4]])

In [59]:
(1**2 + 2**2 + 3**2 + 4**2)**(1/2)

5.477225575051661

In [60]:
np.linalg.norm(X) # same function as for vector L2 norm

5.477225575051661

### Matrix Multiplication (with a Vector)

In [61]:
A = np.array([[3, 4], [5, 6], [7, 8]])
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [62]:
b = np.array([1, 2])
b

array([1, 2])

In [63]:
np.dot(A, b) # even though technically dot products are between vectors only

array([11, 17, 23])

### Matrix Multiplication (with Two Matrices)

In [64]:
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [65]:
B = np.array([[1, 9], [2, 0]])
B

array([[1, 9],
       [2, 0]])

In [66]:
np.dot(A, B)

array([[11, 27],
       [17, 45],
       [23, 63]])

Note that matrix multiplication is not "commutative" (i.e., $AB \neq BA$) so uncommenting the following line will throw a size mismatch error:

In [67]:
# np.dot(B, A)